import type { OCIResource } from './types';

export const nexusTopology: OCIResource[] = [
  { id: 'vcn-oke', name: 'VCN vcn-oke', type: 'vcn', details: '10.110.0.0/16 | Terraform', status: 'active' },
  { id: 'vcn-dev', name: 'VCN-DEV', type: 'vcn', details: '10.6.0.0/16 | shared network manual', status: 'manual' },
  { id: 'drg', name: 'DRG-Invista-Shared', type: 'gateway', details: 'Hub de conectividade entre VCNs', status: 'manual' },
  { id: 'fortigate', name: 'FortiGate', type: 'gateway', details: '129.148.17.8 | borda compartilhada', status: 'active' },
  { id: 'lb-crivo-dev', name: 'Test_Crivo_Dev', type: 'loadbalancer', details: '10.8.4.127 | PRIVATE | host routing MFE/MS', status: 'active' },
  { id: 'apigw-dev', name: 'api-gateway-dev', type: 'apigateway', details: 'PRIVATE | cmp-dev-inv | deployment unificado com rotas MFE + MS', status: 'active' },
  { id: 'apigw-nexus', name: 'api-gateway-nexus-dev', type: 'apigateway', details: 'DELETED em 2026-03-14 | legado', status: 'inactive' },
  { id: 'cls-nexus', name: 'cls-dev-nexus', type: 'cluster', details: 'v1.34.1 | 3 nodes | nexus-services', status: 'active' },
  { id: 'cls-barramento', name: 'cls-dev-barramento', type: 'cluster', details: 'v1.34.1 | 3 nodes | integration-hub', status: 'active' },
  { id: 'cls-observabilidade', name: 'cls-dev-observabilidade', type: 'cluster', details: 'v1.34.1 | 3 nodes | observabilidade', status: 'active' },
  { id: 'lb-nexus-pub', name: 'LB nexus (publico)', type: 'loadbalancer', details: '137.131.236.202 | ingresso publico do cls-dev-nexus', status: 'active' },
  { id: 'lb-nexus-int', name: 'LB nexus internal', type: 'loadbalancer', details: '10.110.143.54 | nginx-internal | ms core', status: 'active' },
  { id: 'lb-barramento', name: 'LB barramento', type: 'loadbalancer', details: '10.110.139.53 | nginx-internal | ms-barramento', status: 'active' },
  { id: 'lb-observ', name: 'LB observabilidade', type: 'loadbalancer', details: '10.110.136.228 | trafego interno observabilidade', status: 'active' },
  { id: 'db-atp', name: 'NEXUS_DEV (AJD)', type: 'database', details: 'Autonomous JSON DB | serverless', status: 'active' },
  { id: 'db-pg-nexus', name: 'NEXUS_DEV (PostgreSQL)', type: 'database', details: 'Banco relacional dos MS nexus', status: 'active' },
  { id: 'db-pg-barramento', name: 'BARRAMENTO_DEV (PostgreSQL)', type: 'database', details: 'Banco relacional do barramento', status: 'active' },
  { id: 'db-redis', name: 'NEXUS_DEV (Redis)', type: 'database', details: 'Cache e sessoes', status: 'active' },
  { id: 'bucket-shell', name: 'mfe-shell-dev', type: 'bucket', details: '/mfe-shell/', status: 'active' },
  { id: 'bucket-auth', name: 'mfe-auth-dev', type: 'bucket', details: '/mfe-auth/', status: 'active' },
  { id: 'bucket-user', name: 'mfe-user-dev', type: 'bucket', details: '/mfe-user/', status: 'active' },
  { id: 'bucket-person', name: 'mfe-person-dev', type: 'bucket', details: '/mfe-person/', status: 'active' },
  { id: 'bucket-poc', name: 'mfe-poc-dev', type: 'bucket', details: '/mfe-poc/', status: 'active' },
  { id: 'bucket-formalization', name: 'mfe-formalization-dev', type: 'bucket', details: '/mfe-formalization/', status: 'active' },
  { id: 'azuredevops', name: 'Azure DevOps', type: 'box', details: 'Repos separados para infra, MFE, MS e topologia', status: 'active' },
  { id: 'vault-nexus', name: 'Vault nexus-api-dev', type: 'shieldcheck', details: 'KMS + secrets | key-nexus-dev', status: 'active' },
  { id: 'domain-nexus', name: 'Identity Domain Nexus', type: 'shieldcheck', details: 'Auth confidencial do app', status: 'active' },
  { id: 'sa-terraform', name: 'svc-terraform', type: 'box', details: 'Service account das pipelines', status: 'active' },
];
